sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t dockerjw20/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dockerjw20/react-test npm run test -- --coverage

after_success:
  - docker build -t dockerjw20/multi-client ./client
  - docker build -t dockerjw20/multi-nginx ./nginx
  - docker build -t dockerjw20/multi-server ./server
  - docker build -t dockerjw20/multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take images and push to dockerhub
  - docker push dockerjw20/multi-client 
  - docker push dockerjw20/multi-nginx
  - docker push dockerjw20/multi-server 
  - docker push dockerjw20/multi-worker 

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-957374566417"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY